### ISSUE TITLE
Agent spawn location in config

### ISSUE THREAD

**Issue by seanysull** [beyretb/AnimalAI-Olympics#64]
I cannot seem to find the right syntax for controlling the agent's spawning location in the documentation.

**Comment by beyretb** [comment]
Same as other elements:

```
!ArenaConfig
arenas:
  0: !Arena
    t: 0
    - !Item
      name: Agent
      positions:
        - !Vector3 {x: 20, y: 1, z: 20}
```
